const express = require('express')
const cors = require('cors')
const dotenv = require('dotenv')
dotenv.config()
const tablesRouter = require('./routes/tables')
const auth = require('./auth')
const app = express()
app.use(cors())
app.use(express.json())
app.use(auth)
app.use('/tables', tablesRouter)
module.exports = app 